name: Update

on:
  watch:
    types: [started]
  schedule:
    - cron: 0,30 * * * *

env:
  TZ: Asia/Shanghai

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: GetTime
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S CST')"

      - name: Update
        run: |
          rm -f CCTV.m3u && wget https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u -O CCTV.m3u
          sed -i -n '/央视频道/,+1p' CCTV.m3u
          sed -i '1i #EXTM3U' CCTV.m3u
          sed -i '/^\s*$/d' CCTV.m3u

          rm -f CNTV.m3u && touch CNTV.m3u
          wget https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u -O CNTV1.m3u && sed -i -n '/卫视频道/,+1p' CNTV1.m3u
          wget https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u -O CNTV2.m3u && sed -i -n '/NewTV系列/,+1p' CNTV2.m3u
          wget https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u -O CNTV3.m3u && sed -i -n '/超清频道/,+1p' CNTV3.m3u
          cat CNTV1.m3u >> CNTV.m3u
          cat CNTV2.m3u >> CNTV.m3u
          cat CNTV3.m3u >> CNTV.m3u
          rm -f CNTV1.m3u CNTV2.m3u CNTV3.m3u
          sed -i '1i #EXTM3U' CNTV.m3u
          sed -i '/^\s*$/d' CNTV.m3u

          rm -f Adult.m3u && wget http://adultiptv.net/chs.m3u -O Adult.m3u
          sed -i 's/XXX/成人频道/' Adult.m3u
          sed -i 's/AdultIPTV.net //g' Adult.m3u
          
          wget https://raw.githubusercontent.com/YanG-1989/m3u/main/Adult.m3u -O AdultVideo.txt
          sed -i 's/group-title="\([^"]*\)"/group-title="成人视频"/' AdultVideo.txt
          cat AdultVideo.txt >> Adult.m3u
          rm -f AdultVideo.txt
          sed -i '/^\s*$/d' Adult.m3u
          sed -i 's#\(http://\|https://\)\(.*m3u8.*\)#https://proxy.ymoo.buzz/\1\2#g' Adult.m3u

          rm -f IHOT.m3u && wget https://raw.githubusercontent.com/Kimentanm/aptv/master/m3u/iptv.m3u -O IHOT.m3u
          sed -i -n '/求索\|IHOT爱\+/,+1p' IHOT.m3u
          sed -i '/iHOT爱怀旧\|iHOT爱经典\|iHOT爱娱乐\|iHOT爱江湖\|iHOT爱探索\|iHOT爱世界\|iHOT爱极限\|iHOT爱解密\|iHOT爱猎奇\|iHOT爱美食\|iHOT爱时尚\|iHOT爱家庭\|iHOT爱都市/,+1d' IHOT.m3u
          sed -i 's/\"浙江求索生活\"/\"求索生活\"/g' IHOT.m3u
          sed -i '1i #EXTM3U' IHOT.m3u
          sed -i '/^\s*$/d' IHOT.m3u

          rm -f IPTV.m3u && touch IPTV.m3u
          cat CCTV.m3u >> IPTV.m3u
          cat CNTV.m3u >> IPTV.m3u
          cat IHOT.m3u >> IPTV.m3u
          sed -i '/#EXTM3U/d' IPTV.m3u
          sed -i '1i #EXTM3U' IPTV.m3u
          sed -i '/^\s*$/d' IPTV.m3u

          rm -f EPG.xml && wget https://epg.112114.xyz/pp.xml -O EPG.xml
          echo "Auto Update IPTV in ${{ steps.date.outputs.date }}" > README.md

      - name: Clean
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -am "${{ steps.date.outputs.date }}"

      - name: Push
        run: git push -f origin main