name: Update

on:
  watch:
    types: [started]
  schedule:
    - cron: 0 10,22 * * *
  push:
    branches:
      - main

env:
  TZ: Asia/Shanghai

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: GetTime
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S CST')"

      - name: Update
        run: |
          # 酒店源m3u
          rm -f itvlist.m3u && wget https://raw.githubusercontent.com/xxoo-qx/tv/main/itvlist.m3u -O itvlist.m3u
          sed -i '/^\s*$/d' itvlist.m3u
          
          # 酒店源txt
          rm -f itvlist.txt && wget https://raw.githubusercontent.com/xxoo-qx/tv/main/itvlist.txt -O IPTV.txt
          sed -i '/^\s*$/d' IPTV.txt
          
          # 央视源
          rm -f CCTV.m3u && wget https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u -O CCTV.m3u
          sed -i -n '/央视频道/,+1p' CCTV.m3u
          sed -i 's/央视频道/央视/' CCTV.m3u
          sed -i '1i #EXTM3U' CCTV.m3u
          sed -i '/^\s*$/d' CCTV.m3u

          # 卫视源
          rm -f CNTV.m3u && touch CNTV.m3u
          wget https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u -O CNTV1.m3u && sed -i -n '/卫视频道/,+1p' CNTV1.m3u
          wget https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u -O CNTV2.m3u && sed -i -n '/NewTV系列/,+1p' CNTV2.m3u
          wget https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u -O CNTV3.m3u && sed -i -n '/上海频道/,+1p' CNTV3.m3u
          wget https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u -O CNTV4.m3u && sed -i -n '/浙江频道/,+1p' CNTV4.m3u
          wget https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u -O CNTV5.m3u && sed -i -n '/陕西频道/,+1p' CNTV5.m3u
          wget https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u -O CNTV6.m3u && sed -i -n '/求索系列/,+1p' CNTV6.m3u
          cat CNTV1.m3u >> CNTV.m3u
          cat CNTV2.m3u >> CNTV.m3u
          cat CNTV3.m3u >> CNTV.m3u
          cat CNTV4.m3u >> CNTV.m3u
          cat CNTV5.m3u >> CNTV.m3u
          cat CNTV6.m3u >> CNTV.m3u
          rm -f CNTV1.m3u CNTV2.m3u CNTV3.m3u CNTV4.m3u CNTV5.m3u CNTV6.m3u
          sed -i 's/卫视频道/卫视/' CNTV.m3u
          sed -i '1i #EXTM3U' CNTV.m3u
          sed -i '/^\s*$/d' CNTV.m3u

          # 成人源
          #rm -f Adult.m3u && wget http://adultiptv.net/chs.m3u -O Adult.m3u
          #sed -i 's/XXX/成人频道/' Adult.m3u
          #sed -i 's/AdultIPTV.net //g' Adult.m3u
          
          wget https://raw.githubusercontent.com/YanG-1989/m3u/main/Adult.m3u -O AdultVideo.txt
          sed -i -n '/日本\|欧美/,+1p' AdultVideo.txt
          sed -i 's/日本/成人视频/g; s/欧美/成人视频/g' AdultVideo.txt
          sed -i '/https:\/\/\(t12\|t15\|t11\|t17\).cdn2020.com:[0-9]\+/{N;d;}' AdultVideo.txt
          echo '' >> Adult.m3u && cat AdultVideo.txt >> Adult.m3u
          rm -f AdultVideo.txt
          sed -i '/^\s*$/d' Adult.m3u
          sed -i 's#\(http://\|https://\)\(.*m3u8.*\)#https://proxy.ymoo.buzz/\1\2#g' Adult.m3u

          #iHOT源
          rm -f IHOT.m3u && wget https://raw.githubusercontent.com/Kimentanm/aptv/master/m3u/iptv.m3u -O IHOT.m3u
          sed -i -n '/求索\|IHOT爱\+/,+1p' IHOT.m3u
          sed -i '/iHOT爱怀旧\|iHOT爱经典\|iHOT爱娱乐\|iHOT爱江湖\|iHOT爱探索\|iHOT爱世界\|iHOT爱极限\|iHOT爱解密\|iHOT爱猎奇\|iHOT爱美食\|iHOT爱时尚\|iHOT爱家庭\|iHOT爱都市/,+1d' IHOT.m3u
          sed -i 's/\"浙江求索生活\"/\"求索生活\"/g' IHOT.m3u
          sed -i '1i #EXTM3U' IHOT.m3u
          sed -i '/^\s*$/d' IHOT.m3u
          
          #轮播源m3u
          sed -i '/^\s*$/d' LIVE.m3u
          
          #轮播源txt
          sed -i '/^\s*$/d' LIVE.txt
          
          #CCTVtxt
          sed -i '/^\s*$/d' CCTV.txt
          
          #MGDYtxt
          sed -i '/^\s*$/d' MGDY.txt

          # 整合源
          rm -f IPTV.m3u && touch IPTV.m3u
          cat itvlist.m3u >> IPTV.m3u
          cat CCTV.m3u >> IPTV.m3u
          cat CNTV.m3u >> IPTV.m3u
          cat IHOT.m3u >> IPTV.m3u
          cat LIVE.m3u >> IPTV.m3u
          cat CCTV.txt >> IPTV.txt
          echo '' >> IPTV.txt && cat MGDY.txt >> IPTV.txt
          echo '' >> IPTV.txt && cat LIVE.txt >> IPTV.txt
          sed -i '/#EXTM3U/d' IPTV.m3u
          sed -i '1i #EXTM3U' IPTV.m3u
          sed -i '/^\s*$/d' IPTV.m3u

          rm -f EPG.xml && wget https://epg.112114.xyz/pp.xml -O EPG.xml
          echo "Auto Update IPTV in ${{ steps.date.outputs.date }}" > README.md

      - name: Clean
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -am "${{ steps.date.outputs.date }}"

      - name: Push
        run: git push -f origin main
